### ISSUE TITLE
Micronaut Data Kapt compilation flakiness

### ISSUE THREAD

**Issue by o-shevchenko** [micronaut-projects/micronaut-data#1400]
### Expected Behavior

Gradle task kaptKotlin pass

### Actual Behaviour

Gradle task kaptKotlin fails from time to time with the following error:
```kotlin
> Task :kaptKotlin
error: Unable to implement Repository method: ConnectionRepository.save(Object entity). No possible implementations found.
```

### Steps To Reproduce

Don't have the stable reproduce, it's flaky.
It looks like a classpath or annotation processing order issue.
```kotlin
package org.myorg.dao

import org.myorg.dto.ConnectionId
import org.myorg.model.Connection
import io.micronaut.data.mongodb.annotation.MongoRepository
import io.micronaut.data.repository.CrudRepository

@MongoRepository
interface ConnectionRepository : CrudRepository<Connection, ConnectionId>
```
```kotlin
@MappedEntity
data class Connection(
    @field:Id
    @GeneratedValue
    var id: ConnectionId = "",
    val name: String
)
```
```kotlin
typealias ConnectionId = String
```

```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.6.10"
    id("org.jetbrains.kotlin.kapt") version "1.6.10"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.6.10"
    id("io.micronaut.application") version "3.3.0"
    id("io.gitlab.arturbosch.detekt") version "1.19.0"
}
...
micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("org.myorg.*")
    }
}
...
dependencies {
    kapt("io.micronaut:micronaut-http-validation")
    kapt("io.micronaut.data:micronaut-data-document-processor:3.3.0")
    kapt("io.micronaut.openapi:micronaut-openapi")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut.data:micronaut-data-mongodb:3.3.0")
    implementation("io.micronaut.mongodb:micronaut-mongo-sync")
    implementation("io.swagger.core.v3:swagger-annotations")
    implementation("jakarta.annotation:jakarta.annotation-api")
    implementation("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-validation")
    implementation("io.projectreactor:reactor-core:3.4.14")

    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")

    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.19.0")

    testImplementation("com.tngtech.archunit:archunit-junit5:0.23.1")
}
```

### Environment Information

- OS Ubuntu 20.04
- Java 17

### Version

3.3.4

**Comment by melix** [comment]
Not on top of my head :/

**Comment by o-shevchenko** [comment]
What can cause such a problem? I tried to change the version of Micronaut Data and order for kapt dependencies, but not sure if it can help. 
Is there anything to look into? Any ideas on how to collect more info and troubleshoot it?

**Comment by stefanos-kalantzis** [comment]
We got (I think) the same error in our build. The interesting part is that it happened with Maven. We run maven with `-T 3`.

Today was the first occurence after ~20 days, with multiple daily builds. So it looks quite rare. Possibly related to the annotationProcessor?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:compile (default-compile) on project xxxxxxxxx: Compilation failure
[ERROR] Unable to implement Repository method: XxxRepository.save(Object entity). No possible implementations found.
```

We use micronaut-data with r2dbc. Version 3.2.2

**Comment by graemerocher** [comment]
@dstepanov perhaps we need to add some kind of debug output flag to the compiler we can get more diagnostics for this error 🤔

**Comment by o-shevchenko** [comment]
> 

I've been running kaptCompile with debug and stack trace flags to collect more info for the last two days. It hasn't failed with flags. Not sure if it's just because I was unlucky to catch that with debug, or compile takes more time now because we have a lot of IO and some race condition is involved.
Once I will collect more or figure out how to reproduce it I will post it here.

**Comment by stefanos-kalantzis** [comment]
I could also run some builds with more logs enabled. any ideas what is relevant here? is `mvn -X` needed? is it enough? or something else?

**Comment by o-shevchenko** [comment]
Collected more logs
Full log in the attached file: 
[kaptKotlin.log](https://github.com/micronaut-projects/micronaut-data/files/8358141/kaptKotlin.log)

```
20:19:44  2022-03-27T17:19:44.471+0000 [ERROR] [system.err] error: Unable to implement Repository method: ConnectionRepository.save(Object entity). No possible implementations found.
20:19:44  2022-03-27T17:19:44.472+0000 [ERROR] [system.err] Note: Generating OpenAPI Documentation
20:19:44  2022-03-27T17:19:44.472+0000 [ERROR] [system.err] Note: Writing OpenAPI YAML to destination: /home/.../build/tmp/kapt3/classes/main/META-INF/swagger/connection-manager-service-0.0.3.yml
20:19:44  2022-03-27T17:19:44.472+0000 [ERROR] [system.err] Note: Writing OpenAPI View to destination: /home/.../build/tmp/kapt3/classes/main/META-INF/swagger/views/redoc/index.html
20:19:44  2022-03-27T17:19:44.473+0000 [ERROR] [system.err] Note: Writing OpenAPI View to destination: /home/.../build/tmp/kapt3/classes/main/META-INF/swagger/views/rapidoc/index.html
20:19:44  2022-03-27T17:19:44.473+0000 [ERROR] [system.err] Note: Writing OpenAPI View to destination: /home/.../build/tmp/kapt3/classes/main/META-INF/swagger/views/swagger-ui/index.html
20:19:44  2022-03-27T17:19:44.473+0000 [ERROR] [system.err] Note: Creating bean classes for 24 type elements
...
20:19:44  2022-03-27T17:19:44.599+0000 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices$Inject] [KOTLIN] Disposed KotlinGradleBuildServices
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':kaptKotlin'.
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > java.lang.reflect.InvocationTargetException (no error message)
20:19:44  2022-03-27T17:19:44.610+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kaptKotlin'.
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
20:19:44  2022-03-27T17:19:44.611+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
```

**Comment by o-shevchenko** [comment]
@melix @graemerocher any thoughts what could be wrong?

**Comment by o-shevchenko** [comment]
Any update here? We are still facing it

**Comment by graemerocher** [comment]
In general it is hard to say. We would need an example attached with steps to reproduce the issue.

**Comment by melix** [comment]
The problem seems to be related to forked compilation not being enabled. We added this to Micronaut Core for the very same reason: https://github.com/micronaut-projects/micronaut-core/blob/cc688195dfb9598c60278ea018f96cdc202ec247/buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle#L28-L29

There is apparently a bug, either in Micronaut, either in Java, or in Gradle, which prevents annotation processors built in the _same project_ to be (re)loaded properly if they are used in the same process as the daemon. Therefore enabling forked compilation should fix the problem.

**Comment by o-shevchenko** [comment]
Thanks, @melix for the answer, let me try to use fork option.
FWIW I tried to disable `kapt.use.worker.api` and `kapt.incremental.apt` but it didn't help.

**Comment by o-shevchenko** [comment]
Unfortunately, enabling `fork` didn't help as well
```
tasks {
    compileJava {
        options.isFork = true
    }

    compileTestJava {
        options.isFork = true
    }

    compileKotlin {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
    compileTestKotlin {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
```
Is there any other workaround to try to apply?

**Comment by graemerocher** [comment]
@dstepanov perhaps we can add debugging to the compiler that can be enabled to try get to the bottom of this?

**Comment by o-shevchenko** [comment]
Thanks a lot for the fix @melix !
I'm still getting the same error after upgrading to Micronaut Data 3.4.0, which should include the fix.
```
constraints {
        implementation("io.micronaut.data:micronaut-data-mongodb:3.4.0") {
            because(
                "Version < 3.4.0 has compilation flakiness bug (See https://github.com/micronaut-projects/micronaut-data/issues/1400)." +
                        "This constrain can be removed once micronaut-core will use micronaut-data 3.4.0+ by default."
            )
        }
    }
    ```
   I expected that fix should be applied (I can't find `AbstractPrefixPatternMethodMatcher` in dependencies though). Will it work properly only after bumping the version in micronaut-core?

**Comment by dstepanov** [comment]
You need mostly processors for that fix.
Do something like:
```
configurations {
    all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'io.micronaut.data') {
                details.useVersion "$micronautDataVersion"
            }
        }
    }
}
```

**Comment by o-shevchenko** [comment]
Getting back to you to say thank you!
We don't experience such an issue anymore.
